# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [14]:
import pandas as pd
import numpy as np
#creating a (6,4) 2D array with random
data = np.random.randint(1,30, size = (6,4))
print(f"Original Array:\n {data}")
df1 = pd.DataFrame(data, columns=['A', 'B', 'C','D'])
print(f"Original DataFrame:\n {df1}")
df1.set_index('A', inplace= True)
print(f'Index With First Column: \n {df1}')


Original Array:
 [[10 19 16 27]
 [15 13 17 20]
 [29  9 17  5]
 [24 20 28 20]
 [12 22  6 20]
 [16 26  3 22]]
Original DataFrame:
     A   B   C   D
0  10  19  16  27
1  15  13  17  20
2  29   9  17   5
3  24  20  28  20
4  12  22   6  20
5  16  26   3  22
Index With First Column: 
      B   C   D
A             
10  19  16  27
15  13  17  20
29   9  17   5
24  20  28  20
12  22   6  20
16  26   3  22


2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [19]:
#create a pandas DataFrame with specified columns and index
df = pd.DataFrame(np.random.randint(1,20, size = (3,3)), columns=['A','B','C'], index = ['X','Y','Z'])
print(f"Original DataFrame: \n {df}")
#access the element at row 'Y' and Column 'B'
# element = df.loc['Y']['B']
element = df.at['Y','B']
print(f"Element at row 'Y' and column 'B':\n {element} ")

Original DataFrame: 
     A   B   C
X  15   7   7
Y  18  13  13
Z  12   2  17
Element at row 'Y' and column 'B':
 13 


### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [20]:
#create a Pandas DataFrame with 3 columns and 5 rows filled with random integers
df = pd.DataFrame(np.random.randint(1,20, size = (5,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n {df}")
#add a new column is the product of the first two columns
df['D']= df['A'] * df['B']
print(f"DataFrame with new columns:\n {df}")


Original DataFrame: 
     A   B   C
0   8   6  17
1   1   4   4
2  10  10  11
3   7   5   5
4  11   3  13
DataFrame with new columns:
     A   B   C    D
0   8   6  17   48
1   1   4   4    4
2  10  10  11  100
3   7   5   5   35
4  11   3  13   33


2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [21]:
#create a pandas DataFrame with 3 columns and 4 rows
df = pd.DataFrame(np.random.randint(1,20, size = (4,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n {df}")

#compute the row_wise and column wise sum
row_sum = df.sum(axis= 1)
col_sum = df.sum(axis= 0)

print(f"Row wise sum: \n {row_sum}")
print(f"Column wise sum: \n {col_sum}")

Original DataFrame: 
     A   B   C
0   4  16   5
1  17  15   1
2  10  10  19
3   4   2   1
Row wise sum: 
 0    25
1    33
2    39
3     7
dtype: int64
Column wise sum: 
 A    35
B    43
C    26
dtype: int64


### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [ ]:
#create a pandas DataFrame with 3 cols and 5 rows
df = pd.DataFrame(np.random.randint(1,20, size = (5,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n {df}")
#introduce some NaN values
df.iloc[0,1]= np.nan
df.iloc[2,2]= np.nan
df.iloc[4,0]= np.nan
print(f"DataFrame with NaN values: \n {df}")

#fill the NaN values with the mean of the respective column
df.fillna(df.mean(), inplace=True)
print(f"DataFrame with NaN values filled: \n {df}")

Original DataFrame: 
     A   B   C
0   3   1   1
1  17  18   6
2   1   6  15
3  19   3   9
4  17   1  12
DataFrame with NaN values: 
       A     B     C
0   3.0   NaN   1.0
1  17.0  18.0   6.0
2   1.0   6.0   NaN
3  19.0   3.0   9.0
4   NaN   1.0  12.0
DataFrame with NaN values filled: 
       A     B     C
0   3.0   7.0   1.0
1  17.0  18.0   6.0
2   1.0   6.0   7.0
3  19.0   3.0   9.0
4  10.0   1.0  12.0


2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [37]:
#Create a Pandas DataFrame with 4 columns and 6 rows
df = pd.DataFrame(np.random.randint(1,50, size= (6,4)), columns=['A','B','C','D'])
print(f"Original DataFrame:\n {df}")

#introduce some NaN values
df.iloc[1,2]= np.nan
df.iloc[2,3]= np.nan
df.iloc[3,1]= np.nan
print(f"DataFrame with NaN values: \n {df}")

#drop the rows with any NaN values
df.dropna(inplace=True)
print(f"DataFrame with NaN values dropped:\n {df}")

Original DataFrame:
     A   B   C   D
0  47  39  13  41
1  12  22  42  41
2  35  27  34   9
3  23  40  42  40
4  49  20  16  33
5  15   8   6   5
DataFrame with NaN values: 
     A     B     C     D
0  47  39.0  13.0  41.0
1  12  22.0   NaN  41.0
2  35  27.0  34.0   NaN
3  23   NaN  42.0  40.0
4  49  20.0  16.0  33.0
5  15   8.0   6.0   5.0
DataFrame with NaN values dropped:
     A     B     C     D
0  47  39.0  13.0  41.0
4  49  20.0  16.0  33.0
5  15   8.0   6.0   5.0


### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [47]:
#Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'
df = pd.DataFrame({'Category': np.random.choice(['A','B','C'], size =10), 'Values': np.random.randint(1,10, size = 10)})
print(f"Original DataFrame:\n {df}")

#group the dataframe by 'Category' and compute the sum and mean of 'Value' for each category
group = df.groupby('Category')['Values'].agg(['sum', 'mean'])
print(f"Groupped DataFrame: \n {group}")


Original DataFrame:
   Category  Values
0        A       2
1        C       4
2        C       3
3        B       8
4        C       5
5        B       7
6        B       2
7        B       4
8        B       6
9        C       6
Groupped DataFrame: 
           sum  mean
Category           
A           2   2.0
B          27   5.4
C          18   4.5


2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [48]:
# Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'
df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], size =10), 'Category': np.random.choice(['A', 'B', 'C'],size = 10), 'Sales': np.random.randint(1,50, size =10)})
print(f"Original DataFrame: \n {df}")

#group the DataFrame by 'Category' and compute the total sales for each category
group1 = df.groupby('Category')['Sales'].sum()
print(f"Gropped DataFrame:\n {group1}")

Original DataFrame: 
   Product Category  Sales
0   Prod3        A      2
1   Prod2        B     10
2   Prod3        B     29
3   Prod3        A     39
4   Prod3        C     24
5   Prod1        C      7
6   Prod1        A     10
7   Prod2        B      7
8   Prod3        C     26
9   Prod1        A     19
Gropped DataFrame:
 Category
A    70
B    46
C    57
Name: Sales, dtype: int64
