# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [2]:
import pandas as pd
import numpy as np
#creating a (6,4) 2D array with random
data = np.random.randint(1,30, size = (6,4))
print(f"Original Array:\n {data}")
df1 = pd.DataFrame(data, columns=['A', 'B', 'C','D'])
print(f"Original DataFrame:\n {df1}")
df1.set_index('A', inplace= True)
print(f'Index With First Column: \n {df1}')


Original Array:
 [[22  1 29 27]
 [28 29 26  4]
 [28 22 13 12]
 [ 5 17  9 19]
 [28  5  5 28]
 [ 7  2  3 21]]
Original DataFrame:
     A   B   C   D
0  22   1  29  27
1  28  29  26   4
2  28  22  13  12
3   5  17   9  19
4  28   5   5  28
5   7   2   3  21
Index With First Column: 
      B   C   D
A             
22   1  29  27
28  29  26   4
28  22  13  12
5   17   9  19
28   5   5  28
7    2   3  21


2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [3]:
#create a pandas DataFrame with specified columns and index
df = pd.DataFrame(np.random.randint(1,20, size = (3,3)), columns=['A','B','C'], index = ['X','Y','Z'])
print(f"Original DataFrame: \n {df}")
#access the element at row 'Y' and Column 'B'
# element = df.loc['Y']['B']
element = df.at['Y','B']
print(f"Element at row 'Y' and column 'B':\n {element} ")

Original DataFrame: 
     A   B   C
X   9  17  12
Y   4  11   7
Z  14   4   8
Element at row 'Y' and column 'B':
 11 


### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [4]:
#create a Pandas DataFrame with 3 columns and 5 rows filled with random integers
df = pd.DataFrame(np.random.randint(1,20, size = (5,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n {df}")
#add a new column is the product of the first two columns
df['D']= df['A'] * df['B']
print(f"DataFrame with new columns:\n {df}")


Original DataFrame: 
     A   B   C
0  18   6  12
1  16  16   6
2  19  10   7
3  11   2  17
4   6   4   5
DataFrame with new columns:
     A   B   C    D
0  18   6  12  108
1  16  16   6  256
2  19  10   7  190
3  11   2  17   22
4   6   4   5   24


2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [5]:
#create a pandas DataFrame with 3 columns and 4 rows
df = pd.DataFrame(np.random.randint(1,20, size = (4,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n {df}")

#compute the row_wise and column wise sum
row_sum = df.sum(axis= 1)
col_sum = df.sum(axis= 0)

print(f"Row wise sum: \n {row_sum}")
print(f"Column wise sum: \n {col_sum}")

Original DataFrame: 
    A   B   C
0  1   5  11
1  6   6  19
2  9  12   5
3  5   4  12
Row wise sum: 
 0    17
1    31
2    26
3    21
dtype: int64
Column wise sum: 
 A    21
B    27
C    47
dtype: int64


### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [6]:
#create a pandas DataFrame with 3 cols and 5 rows
df = pd.DataFrame(np.random.randint(1,20, size = (5,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n {df}")
#introduce some NaN values
df.iloc[0,1]= np.nan
df.iloc[2,2]= np.nan
df.iloc[4,0]= np.nan
print(f"DataFrame with NaN values: \n {df}")

#fill the NaN values with the mean of the respective column
df.fillna(df.mean(), inplace=True)
print(f"DataFrame with NaN values filled: \n {df}")

Original DataFrame: 
     A   B   C
0   6  16   4
1  13  12  10
2  16  15   8
3  14   7  10
4  14   7  14
DataFrame with NaN values: 
       A     B     C
0   6.0   NaN   4.0
1  13.0  12.0  10.0
2  16.0  15.0   NaN
3  14.0   7.0  10.0
4   NaN   7.0  14.0
DataFrame with NaN values filled: 
        A      B     C
0   6.00  10.25   4.0
1  13.00  12.00  10.0
2  16.00  15.00   9.5
3  14.00   7.00  10.0
4  12.25   7.00  14.0


2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [7]:
#Create a Pandas DataFrame with 4 columns and 6 rows
df = pd.DataFrame(np.random.randint(1,50, size= (6,4)), columns=['A','B','C','D'])
print(f"Original DataFrame:\n {df}")

#introduce some NaN values
df.iloc[1,2]= np.nan
df.iloc[2,3]= np.nan
df.iloc[3,1]= np.nan
print(f"DataFrame with NaN values: \n {df}")

#drop the rows with any NaN values
df.dropna(inplace=True)
print(f"DataFrame with NaN values dropped:\n {df}")

Original DataFrame:
     A   B   C   D
0  24  46  29  14
1  16  46  23  46
2  31   3  34  46
3   7  39  12  30
4   6   2  17  32
5  21  47  18   7
DataFrame with NaN values: 
     A     B     C     D
0  24  46.0  29.0  14.0
1  16  46.0   NaN  46.0
2  31   3.0  34.0   NaN
3   7   NaN  12.0  30.0
4   6   2.0  17.0  32.0
5  21  47.0  18.0   7.0
DataFrame with NaN values dropped:
     A     B     C     D
0  24  46.0  29.0  14.0
4   6   2.0  17.0  32.0
5  21  47.0  18.0   7.0


### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [8]:
#Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'
df = pd.DataFrame({'Category': np.random.choice(['A','B','C'], size =10), 'Values': np.random.randint(1,10, size = 10)})
print(f"Original DataFrame:\n {df}")

#group the dataframe by 'Category' and compute the sum and mean of 'Value' for each category
group = df.groupby('Category')['Values'].agg(['sum', 'mean'])
print(f"Groupped DataFrame: \n {group}")


Original DataFrame:
   Category  Values
0        B       2
1        B       6
2        A       7
3        C       7
4        A       6
5        C       8
6        A       1
7        A       4
8        A       5
9        C       6
Groupped DataFrame: 
           sum  mean
Category           
A          23   4.6
B           8   4.0
C          21   7.0


2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [9]:
# Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'
df = pd.DataFrame({'Product': np.random.choice(['Prod1', 'Prod2', 'Prod3'], size =10), 'Category': np.random.choice(['A', 'B', 'C'],size = 10), 'Sales': np.random.randint(1,50, size =10)})
print(f"Original DataFrame: \n {df}")

#group the DataFrame by 'Category' and compute the total sales for each category
group1 = df.groupby('Category')['Sales'].sum()
print(f"Gropped DataFrame:\n {group1}")

Original DataFrame: 
   Product Category  Sales
0   Prod2        B     17
1   Prod2        B     20
2   Prod3        B     45
3   Prod3        A      2
4   Prod3        A     24
5   Prod3        A     36
6   Prod2        C     14
7   Prod3        B     36
8   Prod3        A      9
9   Prod3        C      1
Gropped DataFrame:
 Category
A     71
B    118
C     15
Name: Sales, dtype: int64


### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [10]:
# Create two Pandas DataFrames with a common column
df1 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'], 'Value1': np.random.randint(1, 100, size=4)})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C', 'E'], 'Value2': np.random.randint(1, 100, size=4)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

# Merge the DataFrames using the common column
merged = pd.merge(df1, df2, on='Key')
print("Merged DataFrame:")
print(merged)

DataFrame 1:
  Key  Value1
0   A      48
1   B      82
2   C      33
3   D      48
DataFrame 2:
  Key  Value2
0   A      86
1   B      50
2   C      43
3   E      18
Merged DataFrame:
  Key  Value1  Value2
0   A      48      86
1   B      82      50
2   C      33      43


2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [7]:
#create two pandas dataframe with different columns
import pandas as pd
import numpy as np
df1 = pd.DataFrame({'A': np.random.randint(1,100, size = 3), 'B': np.random.randint(1,100, size =3)})
df2 = pd.DataFrame({'C': np.random.randint(1,100, size =3), 'D': np.random.randint(1,100, size=3)})
print(f"DataFrame1:\n{df1}")
print(f"Dataframe2:\n {df2}")

#concatenate the dataframes along the rows
concat_rows= pd.concat([df1,df2], axis= 0, ignore_index= True)
print(f"Concatenate DataFrame (rows): \n {concat_rows}")

#concatenate the dataframes along the columns
concat_col= pd.concat([df1, df2], axis=1)
print(f"Concatenate DataFrame (columns):\n {concat_col}")

DataFrame1:
    A   B
0  93   6
1  29  25
2  45   5
Dataframe2:
     C   D
0  77  56
1  59  31
2  18   5
Concatenate DataFrame (rows): 
       A     B     C     D
0  93.0   6.0   NaN   NaN
1  29.0  25.0   NaN   NaN
2  45.0   5.0   NaN   NaN
3   NaN   NaN  77.0  56.0
4   NaN   NaN  59.0  31.0
5   NaN   NaN  18.0   5.0
Concatenate DataFrame (columns):
     A   B   C   D
0  93   6  77  56
1  29  25  59  31
2  45   5  18   5


### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [11]:
#create a pandas dataframe with a datetime index and one column filled with random integers
date_range = pd.date_range(start= '2022-01-01', end= '2022-12-31', freq='D')
df = pd.DataFrame(date_range, columns=['date'])

In [13]:
df['data']= np.random.randint(1,100, size = len(date_range))

In [15]:
df.set_index('date', inplace = True)

In [17]:
print(f"Original Dataframe:\n {df}")

Original Dataframe:
             data
date            
2022-01-01    66
2022-01-02    99
2022-01-03     7
2022-01-04    17
2022-01-05    51
...          ...
2022-12-27    29
2022-12-28    84
2022-12-29    29
2022-12-30    39
2022-12-31     6

[365 rows x 1 columns]


In [18]:
df.shape

(365, 1)

In [20]:
#resampling the dataframe to compute monthly mean of the values
#here argument "W"--> weekly, "M"--> monthly
monthly_mean = df.resample('M').mean()
print(f"Monthly mean Dataframe: \n {monthly_mean}")

Monthly mean Dataframe: 
                  data
date                 
2022-01-02  82.500000
2022-01-09  32.428571
2022-01-16  31.571429
2022-01-23  61.428571
2022-01-30  61.857143
2022-02-06  58.000000
2022-02-13  56.000000
2022-02-20  53.571429
2022-02-27  49.285714
2022-03-06  35.571429
2022-03-13  45.142857
2022-03-20  58.428571
2022-03-27  20.428571
2022-04-03  38.571429
2022-04-10  48.571429
2022-04-17  54.000000
2022-04-24  58.000000
2022-05-01  48.428571
2022-05-08  42.000000
2022-05-15  54.000000
2022-05-22  50.571429
2022-05-29  41.857143
2022-06-05  56.142857
2022-06-12  39.142857
2022-06-19  48.285714
2022-06-26  54.714286
2022-07-03  62.857143
2022-07-10  57.000000
2022-07-17  58.857143
2022-07-24  38.571429
2022-07-31  58.000000
2022-08-07  61.857143
2022-08-14  60.285714
2022-08-21  54.428571
2022-08-28  41.571429
2022-09-04  45.571429
2022-09-11  65.285714
2022-09-18  62.714286
2022-09-25  43.857143
2022-10-02  37.571429
2022-10-09  51.714286
2022-10-16  44.714286
2022-1

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [32]:
#Create a Pandas DataFrame with a datetime index ranging from '2021-01-01'
date_range1= pd.date_range(start= '2021-01-01', end ='2021-12-31', freq='D' )
df = pd.DataFrame(date_range1, columns=['date'])
df['data']= np.random.randint(0,100, size =len(date_range1))
df.set_index('date', inplace = True)

In [34]:
print(f"Original DataFrame: {df}")

Original DataFrame:             data
date            
2021-01-01     9
2021-01-02     6
2021-01-03     3
2021-01-04     1
2021-01-05    83
...          ...
2021-12-27    31
2021-12-28    13
2021-12-29    96
2021-12-30    91
2021-12-31    93

[365 rows x 1 columns]


In [36]:
# Compute the rolling mean with a window of 7 days
rolling_mean = df.rolling(window=7).mean()
print(f"Rolling windows DataFrame: {rolling_mean}")

Rolling windows DataFrame:                  data
date                 
2021-01-01        NaN
2021-01-02        NaN
2021-01-03        NaN
2021-01-04        NaN
2021-01-05        NaN
...               ...
2021-12-27  21.571429
2021-12-28  19.285714
2021-12-29  28.285714
2021-12-30  38.000000
2021-12-31  49.285714

[365 rows x 1 columns]


### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [53]:
# Create a Pandas DataFrame with a MultiIndex (hierarchical index)
import pandas as pd
import numpy as np
arrays = [['A','A','B','B'],['one','two','one','two']]
index = pd.MultiIndex.from_arrays(arrays, names = ('Category', 'Subcategory'))
df = pd.DataFrame(np.random.randint(1,100, size = (4,3)), index = index, columns= ['value1', 'value2','value3'])
print(f"MultiIndex Dataframe: \n {df}")

#basic indexing and slicing
print("Indexing at Category 'A':")
print(df.loc['A'])

#slicing
print("Slicing category at'B' and Subcategory 'two ")
print(df.loc[('B', 'two')])


MultiIndex Dataframe: 
                       value1  value2  value3
Category Subcategory                        
A        one               1      65      63
         two              69      14      13
B        one              90      28      96
         two              54       5      28
Indexing at Category 'A':
             value1  value2  value3
Subcategory                        
one               1      65      63
two              69      14      13
Slicing category at'B' and Subcategory 'two 
value1    54
value2     5
value3    28
Name: (B, two), dtype: int64


2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [60]:
# Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'
arrays = [['A','A','B','B','C','C'],['one','two','one','two','one','two']]
index = pd.MultiIndex.from_arrays(arrays, names = ('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1,100, size= (6,3)), index = index, columns=['value1','value2','value3'])

print(f"Multiindex DataFrame: \n {df}")

#compute the sum of values for each 'Category' and 'SubCategory'
sum_values= df.groupby(['Category', 'SubCategory']).sum()
print("Sum of values")
print(sum_values)

Multiindex DataFrame: 
                       value1  value2  value3
Category SubCategory                        
A        one              45      78      67
         two              79      56      35
B        one              82      26      43
         two              99      92      37
C        one              77      37      52
         two              93      30      64
Sum of values
                      value1  value2  value3
Category SubCategory                        
A        one              45      78      67
         two              79      56      35
B        one              82      26      43
         two              99      92      37
C        one              77      37      52
         two              93      30      64


### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [63]:
# Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'
date_range= pd.date_range(start = '2022-01-01', end = '2022-01-10', freq= 'D')
df= pd.DataFrame({'Date': np.random.choice(date_range, size =20), 'Category': np.random.choice(['A','B','C'], size = 20), 'Value': np.random.randint(1,100, size =20) })
print(f"Original DataFrame: \n {df}")

#creating pivot table to compute the sum of 'Value' for rach 'Category' by 'Date'
pivot_table= df.pivot_table(values = 'Value', index ='Date', columns= 'Category', aggfunc='sum')
print(pivot_table)

Original DataFrame: 
          Date Category  Value
0  2022-01-08        C     97
1  2022-01-02        C     20
2  2022-01-02        B     40
3  2022-01-03        C     64
4  2022-01-04        B     95
5  2022-01-01        B     38
6  2022-01-02        A     76
7  2022-01-02        A     34
8  2022-01-03        C     25
9  2022-01-09        B     75
10 2022-01-01        C     23
11 2022-01-07        C     37
12 2022-01-06        B     14
13 2022-01-08        C     50
14 2022-01-10        B     73
15 2022-01-04        B     34
16 2022-01-07        C      9
17 2022-01-05        C     35
18 2022-01-01        B     90
19 2022-01-04        A     92
Category        A      B      C
Date                           
2022-01-01    NaN  128.0   23.0
2022-01-02  110.0   40.0   20.0
2022-01-03    NaN    NaN   89.0
2022-01-04   92.0  129.0    NaN
2022-01-05    NaN    NaN   35.0
2022-01-06    NaN   14.0    NaN
2022-01-07    NaN    NaN   46.0
2022-01-08    NaN    NaN  147.0
2022-01-09    NaN   75.0    

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [64]:
# Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'
df = pd.DataFrame({'Year': np.random.choice([2020, 2021, 2022], size=12), 'Quarter': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=12), 'Revenue': np.random.randint(1, 1000, size=12)})
print("Original DataFrame:")
print(df)
# Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'
pivot_table = df.pivot_table(values='Revenue', index='Year', columns='Quarter', aggfunc='mean')
print("Pivot Table:")
print(pivot_table)

Original DataFrame:
    Year Quarter  Revenue
0   2020      Q1      895
1   2022      Q2      983
2   2021      Q1      855
3   2021      Q4      934
4   2021      Q1      907
5   2020      Q4      889
6   2020      Q2      905
7   2020      Q3      858
8   2020      Q3      753
9   2021      Q2      523
10  2021      Q1      743
11  2020      Q3      723
Pivot Table:
Quarter     Q1     Q2     Q3     Q4
Year                               
2020     895.0  905.0  778.0  889.0
2021     835.0  523.0    NaN  934.0
2022       NaN  983.0    NaN    NaN


### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [68]:
df = pd.DataFrame(np.random.randint(1,100, size= (5,3)), columns=['A','B','C'])
print(f"Original DataFrame: \n{df}")
# Apply a function that doubles the values of the DataFrame
df_doubled = df.map(lambda x: x * 2)
print("Doubled DataFrame:")
print(df_doubled)

Original DataFrame: 
    A   B   C
0  74  56  34
1  98  45  36
2  80  60  26
3  39  47  43
4   4  65  80
Doubled DataFrame:
     A    B    C
0  148  112   68
1  196   90   72
2  160  120   52
3   78   94   86
4    8  130  160


2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [69]:
# Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
print(df)

# Apply a lambda function to create a new column that is the sum of the existing columns
df['Sum'] = df.apply(lambda row: row.sum(), axis=1)
print("DataFrame with Sum column:")
print(df)

Original DataFrame:
    A   B   C
0  60  15  58
1  30  61  67
2  30   8  47
3  18  30  46
4  48  60  27
5  88  36  98
DataFrame with Sum column:
    A   B   C  Sum
0  60  15  58  133
1  30  61  67  158
2  30   8  47   85
3  18  30  46   94
4  48  60  27  135
5  88  36  98  222


### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [70]:
# Create a Pandas Series with 5 random text strings
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_data)

# Convert all the strings to uppercase
uppercase_data = text_data.str.upper()
print("Uppercase Series:")
print(uppercase_data)

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object
Uppercase Series:
0         APPLE
1        BANANA
2        CHERRY
3          DATE
4    ELDERBERRY
dtype: object


2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [71]:
# Create a Pandas Series with 5 random text strings
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_data)

# Extract the first three characters of each string
first_three_chars = text_data.str[:3]
print("First three characters:")
print(first_three_chars)

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object
First three characters:
0    app
1    ban
2    che
3    dat
4    eld
dtype: object
