#### NumPy
NumPy is a fundamental library for scientific scomputing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structure. In this module, we will cover the basics of NumPy, focusing on arrays and vectorized operations. 

In [106]:
import numpy as np

In [107]:
#create arrays with numpy #1-dimentional array

array1 = np.array([1,2,3,4,5,6]) #inside the array we can give list, tuples
print(array1)
print(type(array1))
print(array1.shape) #single dimention it will show one element only 1 number will be available, blank on the other side 

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [108]:
#convert a single dimention arrays into 2 dimention array
array2 = np.array([1,2,3,4,5,])
array2.reshape(1,5) #2 braces so that's a 2d array (1,5)---> 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [109]:
array3 = np.array([[1,2,3,4,5]]) #list inside a list
array3.shape

(1, 5)

In [110]:
#2D ARRAY
array4 = np.array([[1,2,3,4,5],[2,3,4,5,6,]]) #2 list seperated by comma
print(array4)
print(array4.shape) #shape is 2 rows and 5 columns so ---> row will be how many list we provide and and column will be len(list) and each row elements numbers should be same length 

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [111]:
#create arrays with built in functions
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [112]:
#in built functions ones
#create a 2d arrays in 3 rows and 5 columns and all the elements will be 1
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
#identity matrix
np.eye(3) #all the diagnal element will be 1 and remaining will be 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [115]:
##NumPy vectorized operation
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,20,30,40,50,60])

#element wise addition
print("Addition:",arr1+arr2)

#element wise substractions
print("substraction:",arr1-arr2)

#element wise multiplication
print("multiplication:",arr1*arr2)

#element wise division
print("division:",arr1/arr2)






Addition: [11 22 33 44 55 66]
substraction: [ -9 -18 -27 -36 -45 -54]
multiplication: [ 10  40  90 160 250 360]
division: [0.1 0.1 0.1 0.1 0.1 0.1]


In [116]:
#universal functions ---> some functions that apply to the entire array
arr2= np.array([2,3,4,5,6])

#squareroot
print(np.sqrt(arr2))

#exponential
print(np.exp(arr2))

#sine
print(np.sin(arr2))

#natural log
print(np.log(arr2))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [117]:
#array slicing operations and indexing
arr5= np.array([[1,2,3,4,5,6],[6,7,8,9,10,11],[11,12,13,14,15,16]])

In [118]:
print(arr5)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]
 [11 12 13 14 15 16]]


In [119]:
arr5[0][0]

np.int64(1)

In [120]:
#pickup 7,8,9,12,13,14
arr5[1:,1:4] #first slicing is row slicing and second is column slicing



array([[ 7,  8,  9],
       [12, 13, 14]])

In [121]:
#pickup 6,7,11,12
arr5[1:,:2]


array([[ 6,  7],
       [11, 12]])

In [122]:
## modify array elements
arr5[0][0]=100


In [123]:
arr5

array([[100,   2,   3,   4,   5,   6],
       [  6,   7,   8,   9,  10,  11],
       [ 11,  12,  13,  14,  15,  16]])

In [125]:
arr5[1:] 

array([[ 6,  7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15, 16]])

In [128]:
#statistical concept ---> Normalization
## to have a mean 0f 0 and stadard deviation of 1
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalize_data = (data-mean) / std_dev
print(f"Normalize data {normalize_data}")


Normalize data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [129]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [134]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])