#### NumPy
NumPy is a fundamental library for scientific scomputing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structure. In this module, we will cover the basics of NumPy, focusing on arrays and vectorized operations. 

In [106]:
import numpy as np

In [107]:
#create arrays with numpy #1-dimentional array

array1 = np.array([1,2,3,4,5,6]) #inside the array we can give list, tuples
print(array1)
print(type(array1))
print(array1.shape) #single dimention it will show one element only 1 number will be available, blank on the other side 

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [108]:
#convert a single dimention arrays into 2 dimention array
array2 = np.array([1,2,3,4,5,])
array2.reshape(1,5) #2 braces so that's a 2d array (1,5)---> 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [109]:
array3 = np.array([[1,2,3,4,5]]) #list inside a list
array3.shape

(1, 5)

In [110]:
#2D ARRAY
array4 = np.array([[1,2,3,4,5],[2,3,4,5,6,]]) #2 list seperated by comma
print(array4)
print(array4.shape) #shape is 2 rows and 5 columns so ---> row will be how many list we provide and and column will be len(list) and each row elements numbers should be same length 

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [111]:
#create arrays with built in functions
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [112]:
#in built functions ones
#create a 2d arrays in 3 rows and 5 columns and all the elements will be 1
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [113]:
#identity matrix
np.eye(3) #all the diagnal element will be 1 and remaining will be 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [114]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [115]:
##NumPy vectorized operation
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([10,20,30,40,50,60])

#element wise addition
print("Addition:",arr1+arr2)

#element wise substractions
print("substraction:",arr1-arr2)

#element wise multiplication
print("multiplication:",arr1*arr2)

#element wise division
print("division:",arr1/arr2)






Addition: [11 22 33 44 55 66]
substraction: [ -9 -18 -27 -36 -45 -54]
multiplication: [ 10  40  90 160 250 360]
division: [0.1 0.1 0.1 0.1 0.1 0.1]


In [116]:
#universal functions ---> some functions that apply to the entire array
arr2= np.array([2,3,4,5,6])

#squareroot
print(np.sqrt(arr2))

#exponential
print(np.exp(arr2))

#sine
print(np.sin(arr2))

#natural log
print(np.log(arr2))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [117]:
#array slicing operations and indexing
arr5= np.array([[1,2,3,4,5,6],[6,7,8,9,10,11],[11,12,13,14,15,16]])

In [118]:
print(arr5)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]
 [11 12 13 14 15 16]]


In [119]:
arr5[0][0]

np.int64(1)

In [120]:
#pickup 7,8,9,12,13,14
arr5[1:,1:4] #first slicing is row slicing and second is column slicing



array([[ 7,  8,  9],
       [12, 13, 14]])

In [121]:
#pickup 6,7,11,12
arr5[1:,:2]


array([[ 6,  7],
       [11, 12]])

In [122]:
## modify array elements
arr5[0][0]=100


In [123]:
arr5

array([[100,   2,   3,   4,   5,   6],
       [  6,   7,   8,   9,  10,  11],
       [ 11,  12,  13,  14,  15,  16]])

In [125]:
arr5[1:] 

array([[ 6,  7,  8,  9, 10, 11],
       [11, 12, 13, 14, 15, 16]])

In [128]:
#statistical concept ---> Normalization
## to have a mean 0f 0 and stadard deviation of 1
data = np.array([1,2,3,4,5])

#calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalize_data = (data-mean) / std_dev
print(f"Normalize data {normalize_data}")


Normalize data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [129]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)



Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [134]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

#### About np.random funtion

#### random1:
- create array of specified shape and fills it with random value as per uniform distribution
- values will be in [0,1] distribution

In [3]:
import numpy as np
array8= np.random.rand(3,2)
print(array8)

[[0.88736196 0.26974966]
 [0.5857409  0.84713946]
 [0.12071514 0.7633831 ]]


In [4]:
help(np.random.rand)

Help on method rand in module numpy.random:

rand(*args) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)

    Random values in a given shape.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.

    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.

    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.

    See Also
    --------
    random

    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.1402247

#### random 2:
create array of specified shape and fills it with random values as per standard normal distibution

In [5]:
array8 = np.random.randn(3,2)
print(array8)
help(np.random.randn)

[[-0.74229658 -1.20841103]
 [ 1.36360262 -0.14150963]
 [-0.68742784  0.07085843]]
Help on method randn in module numpy.random:

randn(*args) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution

#### random 3:
create array of specified shape and fills it with random floats in the half open interval[0.0, 1.0]


In [12]:
array9= np.random.ranf(12).reshape(3,4)
print(array9)
help(np.random.ranf)

[[0.72767644 0.1002169  0.55708779 0.33783093]
 [0.57470539 0.39022052 0.89717427 0.17810031]
 [0.00358467 0.35943599 0.41752518 0.63175228]]
Help on cython_function_or_method in module numpy.random:

ranf(*args, **kwargs)
    This is an alias of `random_sample`. See `random_sample`  for the complete
    documentation.



#### random 4:
creates array of specified shape and fills it with random integers from low to high.
- lows is inclusive, high is exclusive.
- if high is not mentioned then interval will be [0, low] 

In [14]:
array10= np.random.randint(low=4, size =(2,3))
print(array10)

help(np.random.randint)

[[2 2 0]
 [1 1 1]]
Help on method randint in module numpy.random:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
   