# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [4]:
import numpy as np
array1 = np.random.randint(1,20, size =(5,5))
print('Original array')
print(array1)
#replace all the elements in the third column
array1[:,2]=1

print('Modified array')
print(array1)


Original array
[[18 12  9  7  3]
 [ 1  6 10 16  6]
 [ 5  9  6 19  9]
 [11 12 12  7  7]
 [12  3 19 15  6]]
Modified array
[[18 12  1  7  3]
 [ 1  6  1 16  6]
 [ 5  9  1 19  9]
 [11 12  1  7  7]
 [12  3  1 15  6]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [8]:
array2 = np.arange(1,17).reshape(4,4)
print("original array")
print(array2)
#replace the diagonal elements with 0
np.fill_diagonal(array2,0)
print("modified array")
print(array2)

original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
modified array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [13]:
array3 = np.arange(1,37).reshape(6,6)
print("original array")
print(array3)

#extracting a sub array consisting 3rd to 5th rows and 2nd to 4th column
sub_array3=array3[2:5,1:4]
print("Subarray")
print(sub_array3)

original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Subarray
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [27]:
array4 = np.random.randint(1,21, size = (5,5))
print('original array')
print(array4)
#extract the element on the border
array4[0] #first row
array4[-1,:] #last row
array4[:,0]
array4[:,-1]
border_element= np.concatenate((array4[0,:],array4[-1,:],array4[1:-1,0],array4[1:-1,-1]))
print('Border element')
print(border_element)

original array
[[ 8  9 14  6 20]
 [ 8  4 20 13 16]
 [ 9 16 10  7  1]
 [16  7  6 16  6]
 [11  9  5 16 12]]
Border element
[ 8  9 14  6 20 11  9  5 16 12  8  9 16 16  1  6]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [40]:
array5 = np.random.randint(1,11, size = (3,4))
array6 = np.random.randint(1,11, size = (3,4))
print("Array 1: ")
print(array5)
print("array 2: ")
print(array6)

#perform element wise operations
addition = array5 + array6
substraction = array5 - array6
multiplication = array5 * array6
division = array5 / array6

print(f"Element wise addition:\n {addition}")
print(f"Element wise substraction:\n {substraction}")
print(f"Element wise multiplication:\n {multiplication}")
print(f"Element wise division:\n {division}")



Array 1: 
[[ 8  8  2  1]
 [ 3 10  3 10]
 [10 10  3  5]]
array 2: 
[[ 6  3  6 10]
 [10  6  9  1]
 [ 1  4  6  2]]
Element wise addition:
 [[14 11  8 11]
 [13 16 12 11]
 [11 14  9  7]]
Element wise substraction:
 [[ 2  5 -4 -9]
 [-7  4 -6  9]
 [ 9  6 -3  3]]
Element wise multiplication:
 [[48 24 12 10]
 [30 60 27 10]
 [10 40 18 10]]
Element wise division:
 [[ 1.33333333  2.66666667  0.33333333  0.1       ]
 [ 0.3         1.66666667  0.33333333 10.        ]
 [10.          2.5         0.5         2.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [46]:
array7 = np.arange(1,17).reshape(4,4)
print("Original Array")
print(array7)
row_sum = np.sum(array7, axis=1)
column_sum = np.sum(array7, axis=0)

print(f"Row wise sum:\n {row_sum}")
print(f"Column wise sum:\n{column_sum}")

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum:
 [10 26 42 58]
Column wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [51]:
array8 = np.random.randint(1,20, size = (5,5))
print("Original Array")
print(array8)

#find the mean
mean = np.mean(array8)

#find the median
median = np.median(array8)

#find the std 
std = np.std(array8)

#find the variance
variance = np.var(array8)

print(f"Mean value of the array:\n {mean}")
print(f"Median value of the array:\n {median}")
print(f"standard deviation value of the array:\n {std}")
print(f"Variance value of the array:\n {variance}")

Original Array
[[11 12  3  5  5]
 [ 4  5  6  8  2]
 [14 14  7  7  1]
 [19 10 12  7 14]
 [11 11 11  8 16]]
Mean value of the array:
 8.92
Median value of the array:
 8.0
standard deviation value of the array:
 4.489276110911423
Variance value of the array:
 20.153599999999997


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [55]:
array9 = np.arange(1,10).reshape(3,3)
print("Original array")
print(array9)

#Normalize the array
mean = np.mean(array9)
std = np.std(array9)
normalized_array = (array9-mean) / std

print(f"Normalized array:\n {normalized_array}")


Original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
