# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [4]:
import numpy as np
array1 = np.random.randint(1,20, size =(5,5))
print('Original array')
print(array1)
#replace all the elements in the third column
array1[:,2]=1

print('Modified array')
print(array1)


Original array
[[18 12  9  7  3]
 [ 1  6 10 16  6]
 [ 5  9  6 19  9]
 [11 12 12  7  7]
 [12  3 19 15  6]]
Modified array
[[18 12  1  7  3]
 [ 1  6  1 16  6]
 [ 5  9  1 19  9]
 [11 12  1  7  7]
 [12  3  1 15  6]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [8]:
array2 = np.arange(1,17).reshape(4,4)
print("original array")
print(array2)
#replace the diagonal elements with 0
np.fill_diagonal(array2,0)
print("modified array")
print(array2)

original array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
modified array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [13]:
array3 = np.arange(1,37).reshape(6,6)
print("original array")
print(array3)

#extracting a sub array consisting 3rd to 5th rows and 2nd to 4th column
sub_array3=array3[2:5,1:4]
print("Subarray")
print(sub_array3)

original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Subarray
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [27]:
array4 = np.random.randint(1,21, size = (5,5))
print('original array')
print(array4)
#extract the element on the border
array4[0] #first row
array4[-1,:] #last row
array4[:,0]
array4[:,-1]
border_element= np.concatenate((array4[0,:],array4[-1,:],array4[1:-1,0],array4[1:-1,-1]))
print('Border element')
print(border_element)

original array
[[ 8  9 14  6 20]
 [ 8  4 20 13 16]
 [ 9 16 10  7  1]
 [16  7  6 16  6]
 [11  9  5 16 12]]
Border element
[ 8  9 14  6 20 11  9  5 16 12  8  9 16 16  1  6]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [40]:
array5 = np.random.randint(1,11, size = (3,4))
array6 = np.random.randint(1,11, size = (3,4))
print("Array 1: ")
print(array5)
print("array 2: ")
print(array6)

#perform element wise operations
addition = array5 + array6
substraction = array5 - array6
multiplication = array5 * array6
division = array5 / array6

print(f"Element wise addition:\n {addition}")
print(f"Element wise substraction:\n {substraction}")
print(f"Element wise multiplication:\n {multiplication}")
print(f"Element wise division:\n {division}")



Array 1: 
[[ 8  8  2  1]
 [ 3 10  3 10]
 [10 10  3  5]]
array 2: 
[[ 6  3  6 10]
 [10  6  9  1]
 [ 1  4  6  2]]
Element wise addition:
 [[14 11  8 11]
 [13 16 12 11]
 [11 14  9  7]]
Element wise substraction:
 [[ 2  5 -4 -9]
 [-7  4 -6  9]
 [ 9  6 -3  3]]
Element wise multiplication:
 [[48 24 12 10]
 [30 60 27 10]
 [10 40 18 10]]
Element wise division:
 [[ 1.33333333  2.66666667  0.33333333  0.1       ]
 [ 0.3         1.66666667  0.33333333 10.        ]
 [10.          2.5         0.5         2.5       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [46]:
array7 = np.arange(1,17).reshape(4,4)
print("Original Array")
print(array7)
row_sum = np.sum(array7, axis=1)
column_sum = np.sum(array7, axis=0)

print(f"Row wise sum:\n {row_sum}")
print(f"Column wise sum:\n{column_sum}")

Original Array
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum:
 [10 26 42 58]
Column wise sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [51]:
array8 = np.random.randint(1,20, size = (5,5))
print("Original Array")
print(array8)

#find the mean
mean = np.mean(array8)

#find the median
median = np.median(array8)

#find the std 
std = np.std(array8)

#find the variance
variance = np.var(array8)

print(f"Mean value of the array:\n {mean}")
print(f"Median value of the array:\n {median}")
print(f"standard deviation value of the array:\n {std}")
print(f"Variance value of the array:\n {variance}")

Original Array
[[11 12  3  5  5]
 [ 4  5  6  8  2]
 [14 14  7  7  1]
 [19 10 12  7 14]
 [11 11 11  8 16]]
Mean value of the array:
 8.92
Median value of the array:
 8.0
standard deviation value of the array:
 4.489276110911423
Variance value of the array:
 20.153599999999997


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [55]:
array9 = np.arange(1,10).reshape(3,3)
print("Original array")
print(array9)

#Normalize the array
mean = np.mean(array9)
std = np.std(array9)
normalized_array = (array9-mean) / std

print(f"Normalized array:\n {normalized_array}")


Original array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [57]:
array10= np.random.randint(1,10, size=(3,3))
row_array10= np.random.randint(1,10, size=(3,))
print(f"Original Array:\n {array10}")
print(f"1D array:\n {row_array10} ")
# Add the 1D array to each row of the 2D array using broadcasting
result = array10 + row_array10
print(f"resulting array:\n {result}")

Original Array:
 [[4 8 7]
 [3 1 7]
 [6 9 9]]
1D array:
 [3 4 2] 
resulting array:
 [[ 7 12  9]
 [ 6  5  9]
 [ 9 13 11]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [62]:
array11= np.random.randint(1,10, size= (4,4))
column_array11= np.random.randint(1,10, size =(4,))
print(f"Original array:\n {array11}")
print(f"1D array:\n {column_array11}")

# Subtract the 1D array from each column of the 2D array using broadcasting
# column_array11[:,np.newaxis] making row into column
result = array11- column_array11[:, np.newaxis]
print(f"resulting array:\n {result}")



Original array:
 [[4 3 9 5]
 [4 8 1 7]
 [6 6 7 9]
 [8 6 7 1]]
1D array:
 [1 5 8 9]
resulting array:
 [[ 3  2  8  4]
 [-1  3 -4  2]
 [-2 -2 -1  1]
 [-1 -3 -2 -8]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [72]:
# Create a NumPy array of shape (3, 3) representing a matrix
array12 = np.random.randint(1,11, size=(3,3))
print(f"Original matrix: \n {array12}")

#compute its determinant
determinant= np.linalg.det(array12)
print(f"Determinant: \n {determinant}")

#computer inverse
inverse = np.linalg.inv(array12)
print(f"Inverse: \n {inverse}")

#compute eigenvalues
eigen_values = np.linalg.eigvals(array12)
print(f"EigenValues: \n {eigen_values}")



Original matrix: 
 [[ 5  5  2]
 [ 5  6  4]
 [ 6  4 10]]
Determinant: 
 57.999999999999986
Inverse: 
 [[ 0.75862069 -0.72413793  0.13793103]
 [-0.44827586  0.65517241 -0.17241379]
 [-0.27586207  0.17241379  0.0862069 ]]
EigenValues: 
 [15.6909911   0.82420248  4.48480643]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [74]:
array13 = np.random.randint(1,11, size = (2,3))
array14 = np.random.randint(1,11, size = (3,2))
print(f"Array 1:\n {array13}")
print(f"array 2:\n {array14}")

#perform the matrix multiplication
result = np.dot(array13, array14)
print(f"Matrix multiplication result:\n {result}")

Array 1:
 [[4 5 8]
 [8 9 6]]
array 2:
 [[ 9  4]
 [ 8  7]
 [10  2]]
Matrix multiplication result:
 [[156  67]
 [204 107]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [77]:
array15= np.arange(1,10).reshape(3,3)
array16= array15.reshape(1,9)
print(f"Original array: (1,9)\n {array15}")
print(f"Reshaping array: \n {array16}")
#reshaping again
array17= array16.reshape(9,1)
print(f"2nd Reshaping array:(9,1) \n {array17}")

Original array: (1,9)
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaping array: 
 [[1 2 3 4 5 6 7 8 9]]
2nd Reshaping array:(9,1) 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [81]:
array18 = np.random.randint(1,20, size = (5,5))
print(f"Original array: \n {array18}")
#2 ways to flaten the array
array19= array18.reshape(1,25)
array20 = array18.flatten()
print(f"Flatten array: \n {array19}")
print(f"Flatten array: \n {array20}")

#reshaping the array
array21= array20.reshape(5,5)
print(f"reshaped array:(5,5)\n {array21}")

Original array: 
 [[19  8  7 13 19]
 [ 6 16  7 10  4]
 [19  9 11  3 11]
 [ 6 18 13  1  4]
 [11 11  7  1 10]]
Flatten array: 
 [[19  8  7 13 19  6 16  7 10  4 19  9 11  3 11  6 18 13  1  4 11 11  7  1
  10]]
Flatten array: 
 [19  8  7 13 19  6 16  7 10  4 19  9 11  3 11  6 18 13  1  4 11 11  7  1
 10]
reshaped array:(5,5)
 [[19  8  7 13 19]
 [ 6 16  7 10  4]
 [19  9 11  3 11]
 [ 6 18 13  1  4]
 [11 11  7  1 10]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [103]:
array22= np.random.randint(1,20, size = (5,5))
print(f"Original array:\n {array22}")

# Use fancy indexing to extract the elements at the corners of the array
# corners1 = array22[0,0]
# corners2 = array22[0,-1]
# corners3 = array22[-1,0]
# corners4 = array22[-1,-1]
corner = array22[[ 0, 0, -1, -1],[0, -1, 0, -1]]

print(f"corners:\n {corner}")


Original array:
 [[ 3 12 12  5 10]
 [11 19 19  3 14]
 [18  3 17  8 13]
 [ 3 10 18 17 12]
 [ 3  2 18 16 16]]
corners:
 [ 3 10  3 16]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [110]:
array23 = np.random.randint(1,20, size= (4,4))
print(f"Original array: \n {array23}")

# Use boolean indexing to set all elements greater than 10 to 10
array23[array23>10]=10
print(f"Modified array:\n {array23}")



Original array: 
 [[19 18 18 19]
 [19  3 19  8]
 [ 7  8 18  2]
 [10 19  1  3]]
Modified array:
 [[10 10 10 10]
 [10  3 10  8]
 [ 7  8 10  2]
 [10 10  1  3]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [123]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'),('age','i4'),('weight','f4')]
data = np.array([('rhs2', 25, 30.5),('sio', 40, 30.2),('rhs6', 30, 50.3)], dtype = data_type)
print(f"Original array: \n {data}")

#sort the array by age
sorted_data = np.sort(data, order='age')
print(f"Sorted array by age:\n {sorted_data}")

Original array: 
 [('rhs2', 25, 30.5) ('sio', 40, 30.2) ('rhs6', 30, 50.3)]
Sorted array by age:
 [('rhs2', 25, 30.5) ('rhs6', 30, 50.3) ('sio', 40, 30.2)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [130]:
data_type = [('x','i4'), ('y', 'i4')]
data1 = np.array([(1,2), (3,4), (5,6)], dtype = data_type)
print(f"Original array:\n {data1}")

# Compute the Euclidean distance between each pair of points
# distance = np.sqrt((data1['x'][:, np.newaxis]-data1['x'])**2 + (data1['y'][:, np.newaxis] - data1['y'])**2)
distance = np.sqrt((data1['x'][:,np.newaxis]-data1['x'])**2 + (data1['y'][:,np.newaxis]-data1['y'])**2)
print(f"educlidean value:\n {distance}")

Original array:
 [(1, 2) (3, 4) (5, 6)]
educlidean value:
 [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [134]:
import numpy.ma as ma
# Create a masked array of shape (4, 4) with random integers
array25=  np.random.randint(1,20, size = (4,4))
masked_array = ma.masked_greater(array25,10)
print(f"Original Array:\n {array25}")
print(f"Masked Array:\n {masked_array}")

#compute the sum od the masked element
sum_masked_array = np.sum(masked_array)
sum_m= masked_array.sum()

print(f"Sum of the masked array: \n {sum_masked_array}")
print(f"sum of the masked array:\n {sum_m}")



Original Array:
 [[ 9  5 15 14]
 [19  4 18 16]
 [14 19 14 11]
 [14  4 12  9]]
Masked Array:
 [[9 5 -- --]
 [-- 4 -- --]
 [-- -- -- --]
 [-- 4 -- 9]]
Sum of the masked array: 
 31
sum of the masked array:
 31


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [137]:
# Create a masked array of shape (3, 3) with random integers
import numpy.ma as ma
array27= np.random.randint(1,21, size = (3,3))
masked_array1= ma.masked_array(array27, mask= np.eye(3, dtype = bool))
print(f"Original array: \n {array27}")
print(f"Masked array: \n {masked_array1}")

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array1.mean()
masked_array2= masked_array1.filled(mean_unmasked)
print(f"Modified masked array: \n {masked_array2}")

Original array: 
 [[13 14  5]
 [ 5 10 14]
 [16  9 19]]
Masked array: 
 [[-- 14 5]
 [5 -- 14]
 [16 9 --]]
Modified masked array: 
 [[10 14  5]
 [ 5 10 14]
 [16  9 10]]
